include: package:quasi_flutter/analysis_options.yaml

linter:
  rules: # Disabled to avoid overloading with warnings
    public_member_api_docs: false
    diagnostic_describe_all_properties: false
    avoid_positional_boolean_parameters: false # Avoid causing incompatibilites with FlutterFlow
